# Generated by Django 4.1.2 on 2022-11-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='hora_entrada',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hora_salida',
            field=models.TimeField(null=True),
        ),
    ]
