# Generated by Django 4.1.2 on 2022-11-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietarios',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='documento',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
