# Generated by Django 4.1.2 on 2022-11-10 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marca_alter_vehiculos_año_alter_vehiculos_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='observaciones',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('valor', models.FloatField(null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Terminado', 'Terminado')], default='Activo', max_length=15)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propietarios')),
            ],
        ),
    ]
